version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2  # İki replikasyonlu Spring Boot uygulaması
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bookproject
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_REDIS_HOST=redis
      - SERVER_PORT=8080
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: bookproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_cache
    networks:
      - app_network

networks:
  app_network:

volumes:
  pg_data:
